image: node:14.15.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - yarn install
  - yarn run build
  - cp -r docs/.vuepress/dist/* public/

  artifacts:
    paths:
        - public/
  
  only:
  - master
